/*
 * File: app/controller/Cars.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Comments', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'detailPanel',
            selector: '#detailPanel'
        },
        {
            ref: 'commentdetailPanel',
            selector: '#centerPanel #commentdetailPanel'
        }
        
    ],

    onGridpanelSelect: function(rowmodel, record, index, eOpts) {

        // Get view references
        var detailPanel = this.getDetailPanel(),
        commentdetailPanel=this.getCommentdetailPanel();
        // Update details panel with data
        detailPanel.update(record.data);
        commentdetailPanel.update(record.data);
  
    },

    init: function(application) {
        this.control({
            "#commentGrid": {
                select: this.onGridpanelSelect
            },
        });
    }

});
