/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CommentView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.commentview',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.XTemplate',
        'Ext.chart.Chart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Column'
    ],

    itemId: 'commentview',
    layout: 'border',

    initComponent: function() {
        var me = this;
        var sm=new Ext.selection.CheckboxModel();
        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'leftPanel',
                    width: 700,
                    title: '评论列表',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            itemId: 'commentGrid',
                            store: 'CommentDataStore',
                            forceFit:true,
                            stripeRows:true,
                            selModel:sm,
                            multiSelect: true,
                            columns: [
                                new Ext.grid.RowNumberer(),
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'id',
                                    text: '编号',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'name1',
                                    text: '商品名称',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'name2',
                                    text: '户主昵称',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'comment',
                                    text: '评论者',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'type',
                                    text: '评论等级',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'img',
                                    text: '图片',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'des',
                                    text: '评论信息',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    format:'Y-m-d',
                                    text: '注册日期',                             
                                    editor: {
                                        xtype: 'datefield'
                                    }
                                },
                            ],
                            viewConfig: {
                            	plugins:{
                            		ptype:'gridviewdragdrop'
                            	}                       	
                            },
                        bbar:new Ext.PagingToolbar({
                        	pageSize:5,
                        	store:'CommentDataStore',
                        	displayInfo:true,
                        	//displayMsg:'显示第{0}条记录到{1}条记录，一共{2}条',
                        	emptyMsg:'没有记录',
                        	plugins:new Ext.ux.ProgressBarPager(),
                        }),
                        plugins: [
                                  Ext.create('Ext.grid.plugin.RowEditing', {

                                  })
                              ]
                       
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'centerPanel',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            split: true,
                            width:'60%',
                            itemId: 'commentdetailPanel',
                            tpl: [
                                '<div style="padding: 10px">',
                                '    <img src="data/{img}" style="float: right; border: 10px solid #999" />',
                                '    <div style="font-size: 15px"><b>商品名称</b>: {name1}<br></div>',
                                '    <div style="font-size: 15px"><b>户主昵称</b>: <a href=" " target="_blank">{name2}</a><br></div>',
                                '    <div style="font-size: 15px"><b>评论者</b>:   {comment}<br></div>',
                                '    <div style="font-size: 15px"><b>评论等级</b>: {type}<br></div>',
                                '</div>'
                            ],
                            layout: 'fit',
                            title: '评论简介'
                        },
                        
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'west',
                            split: true,
                            width:'40%',
                            itemId: 'detailPanel',
                            //此处添加详细评论
                            tpl: [
                                '<div style="padding: 20px">',
                                '<div style="font-size: 18px"><b>评论详细信息</b>: </br>{des}<br></div>',
                                '</div>'
                            ],
                            layout: 'fit',
                            title: '评论详情'
                        },        
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'south',
                            split: true,
                            height: 150,
                            itemId: 'commentPanel',
                            //此处添加chart图
                            html:'<div><iframe src ="ReloadChart.html" height="280" width="100%" frameborder="0"></iframe></div>',
                            layout: 'fit',
                            title: '详细分布',
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});