/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height:  80,
                    itemId: 'headerPanel',
                    title: '易物网后台管理',
                    dockedItems: [
                                  {
                                      xtype: 'toolbar',
                                      dock: 'right',
                                      itemId: 'mainToolbar',
                                      items: [
                                          {
                                              xtype: 'label'
                                          },
                                         
                                          {
                                              xtype: 'button',
                                              itemId: 'removeButton',
                                              icon: 'resources/images/delete.png',
                                              text: '退出系统',
                                              url:''
                                          }
                                      ]
                                  }
                              ],
                  
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    itemId: 'contentPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'tab1',
                            title: '用户注册信息',
                            html:'<div><iframe id="iframe1" src ="record.html" height="500" width="100%" frameborder="0"></iframe></div>'
                        },
                        {
                            xtype: 'panel',
                            itemId: 'tab2',
                            title: '店铺注册信息',
                            html:'<div><iframe id="iframe2" src ="shop.html" height="500" width="100%"  frameborder="0"></iframe></div>'
                        },
                        {
                            xtype: 'panel',
                            itemId: 'tab3',
                            title: '商品评论信息',
                            html:'<div><iframe id="iframe3"src ="comment.html" height="500" width="100%" frameborder="0"></iframe></div>'
                        }
                    ]
                }
            ]
        });
        me.callParent(arguments);
    },
});