/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    itemId: 'headerPanel',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 80,
                    itemId: 'headerPanel',
                    title: '易物网后台管理',
                    dockedItems: [
                                  {
                                      xtype: 'toolbar',
                                      dock: 'right',
                                      itemId: 'mainToolbar',
                                      items: [
                                          {
                                              xtype: 'label'
                                          },
                                         
                                          {
                                              xtype: 'button',
                                              itemId: 'removeButton',
                                              icon: 'resources/images/delete.png',
                                              text: '退出系统',
                                              url:''
                                          }
                                      ]
                                  }
                              ],
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel1',
                    title: '内容', 
                    html:'<iframe id="iframe1" src ="record.html" height="500" width="100%" frameborder="0"></iframe>',
                    hidden:true,
                    
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel2',
                    title: '内容',  
                    html:'<iframe id="iframe2" src ="shop.html" height="500" width="100%" frameborder="0"></iframe>',
                    hidden:true
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel3',
                    title: '内容',  
                    html:'<iframe id="iframe3" src ="comment.html" height="500" width="100%" frameborder="0"></iframe>',
                    hidden:true
                },
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 231,
                    title: '后台管理',                              
                    root: {
                        expanded: true,
                        text: '管理目录 ',
                        children: [
                            {
                                text: '用户管理',
                                expanded: true,
                                children: [
                                    {
                                        text: '用户信息',
                                        leaf: true,
                                        itemId:'node1',
                                    },
                                ]
                            },
                            {
                                text: '店铺管理',
                                expanded: true,
                                children: [
                                    {
                                        text: '店铺信息',
                                        leaf: true,
                                        itemId:'node2',
                                    },
                                ]
                            },
                            {
                                text: '评论管理',
                                expanded: true,
                                children: [
                                    {
                                        text: '评论信息',
                                        leaf: true,
                                        itemId:'node3',
                                    },
                                ]
                            }
                        ]
                    },
                   // store: 'MenuStore',
                viewConfig: {
                       itemId: 'treeMenu'
                }
                },
               {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    title: '内容', 
                    hidden:false
                },
                
            ]
        });

        me.callParent(arguments);
    }

});

