/*
 * File: app/view/RecordForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShopForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.shopform',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    height: 300,
    itemId: 'shopForm',
    width: 475,
    layout: 'fit',
    manageHeight: false,
    title: '增加记录',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            bodyStyle: {
                'background-color': '#fff'
            },
            items: [
                {
                    xtype: 'form',
                    border: 0,
                    itemId: 'form',
                    layout: 'auto',
                    bodyBorder: false,
                    bodyPadding: 20,
                    manageHeight: false,
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 10',
                            fieldLabel: '店铺名称',
                            labelAlign: 'right',
                            name: 'name1',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10',
                            fieldLabel: '户主昵称',
                            labelAlign: 'right',
                            name: 'name2',
                            validateBlank: true
                        },
                        {
                            xtype: 'datefield',
                            margin: '0 0 10',
                            fieldLabel: '注册日期',
                            labelAlign: 'right',
                            name: 'date'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '常用邮箱',
                            labelAlign: 'right',
                            name: 'email',
                            validateBlank: true
                        },
                        {
                            xtype: 'textareafield',
                            margin: '0 0 10',
                            fieldLabel: '店铺描述',
                            labelAlign: 'right',
                            name: 'describe',
                            cols: 30,
                            rows: 1
                        },
                        {
                            xtype: 'container',
                            padding: '10 10 10 10',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'saveButton',
                                    margin: '5 5 5 5 ',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    id: 'cancelButton',
                                    margin: '5 5 5 5',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});